version: '3'
services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/data/db
    
  webapp:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/site
    ports:
      - 8000:8000
    depends_on:
      - mongodb

volumes:
  mongodbdata: