version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: SocialListening
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Password123
    ports:
      - 5432:5432
    volumes:
      - postgresdata:/var/lib/postgresql/data

  webapp:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/site
    ports:
      - 8000:8000
    depends_on:
      - postgres

volumes:
  postgresdata:
