# Generated by Django 4.0.10 on 2024-07-13 08:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbr', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_id', models.PositiveIntegerField()),
                ('user_id', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('post_id', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('content_type', models.CharField(max_length=255)),
                ('post_date', models.DateTimeField()),
                ('url', models.URLField()),
                ('country', models.CharField(max_length=255)),
                ('likes', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('shares', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('num_comments', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('comments', models.JSONField()),
                ('last_updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=50)),
                ('domain_name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('api_key', models.CharField(max_length=150)),
                ('api_secret', models.CharField(max_length=150)),
                ('access_token', models.CharField(max_length=150)),
                ('access_token_secret', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
