# Generated by Django 4.0.10 on 2024-07-17 17:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbr', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=50)),
                ('domain_name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('api_key', models.CharField(max_length=150)),
                ('api_secret', models.CharField(max_length=150)),
                ('access_token', models.CharField(max_length=150)),
                ('access_token_secret', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('post_id', models.CharField(max_length=255, unique=True)),
                ('likes', models.JSONField(default=list)),
                ('num_comments', models.JSONField(default=list)),
                ('shares', models.JSONField(default=list)),
                ('post_date', models.DateField()),
                ('content', models.TextField()),
                ('user_provided_id', models.CharField(max_length=255)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('positive_score', models.FloatField(default=0.0)),
                ('neutral_score', models.FloatField(default=0.0)),
                ('bad_score', models.FloatField(default=0.0)),
                ('frequency', models.IntegerField(default=0)),
                ('comments', models.JSONField(default=list)),
                ('likes_growth_rates', models.JSONField(default=list)),
                ('shares_growth_rates', models.JSONField(default=list)),
                ('num_comments_growth_rates', models.JSONField(default=list)),
                ('switch_status', models.BooleanField(default=False)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.socialmediaplatform')),
            ],
        ),
    ]
